consumablesList = [
"Bone Dart (5x)",
"Crystal Dart (3x)",
"Poisonbone Dart (5x)",
"Fire Pot (3x)",
"Roped Fire Pot (3x)",
"Fetid Pot (3x)",
"Roped Fetid Pot (3x)",
"Poison Pot (3x)",
"Roped Poison Pot (3x)",
"Oil Pot (1x) and Fire Pot (1x)",
"Roped Oil Pot (1x) and Roped Fire Pot (1x)",
"Magic Pot (3x)",
"Roped Magic Pot (3x)",
"Lightning Pot (3x)",
"Roped Lightning Pot (3x)",
"Holy Water Pot (3x)",
"Roped Holy Water Pot (3x)",
"Fly or Swarm Pot (2x)",
"(Roped Fly or) Swarm Pot (2x)",
"Volcano Pot (3x)",
"Roped Volcano Pot (3x)",
"Rot Pot (2x)",
"Sacred Order Pot (2x)",
"Redmane Fire Pot (2x)",
"Rancor Pot (2x)",
"Giantsflame Fire Pot (2x)",
"Freezing Pot (2x)",
"Academy Magic Pot (2x)",
"Ancient Dragonbolt Pot (2x)",
"Cursed-Blood Pot (2x)",
"Albinauric Pot (3x)",
"Sleep Pot (2x)",
"Poison Spraymist",
"Uplifting Aromatic",
"Ironjar Aromatic",
"Spark Aromatic",
"Acid Spraymist",
"Bloodboil Aromatic",
"Fire Grease (2x)",
"Drawstring Fire Grease (3x)",
"Magic Grease (2x)",
"Drawstring Magic Grease (3x)",
"Blood Grease (2x)",
"Drawstring Blood Grease (3x)",
"Lightning Grease (2x)",
"Drawstring Lightning Grease (3x)",
"Holy Grease (2x)",
"Drawstring Holy Grease (3x)",
"Poison Grease (2x)",
"Drawstring Poison Grease (3x)",
"Rot Grease",
"Drawstring Rot Grease",
"Soporific Grease (2x)",
"Drawstring Soporific Grease (3x)",
"Freezing Grease (2x)",
"Shield Grease (3x)",
"Messmerfire Grease",
"Drawstring Messmerfire Grease",
"Dragonbolt Grease",
"Drawstring Dragonbolt Grease",
"Royal Magic Grease",
"Drawstring Royal Magic Grease",
"Golden Grease",
"Drawstring Golden Grease",
"Eternal Sleep Grease",
"Drawstring Eternal Sleep Grease",
"Dragon Communion Grease",
"Drawstring Dragon Communion Grease",
"Clarifying Cured Meat",
"Clarifying White Cured Meat",
"Immunizing Cured Meat",
"Immunizing White Cured Meat",
"Invigorating Cured Meat",
"Invigorating White Cured Meat",
"Dappled Cured Meat",
"Dappled White Cured Meat",
"Stanching Boluses (2x)",
"Stimulating Boluses (2x)",
"Rejuvenating Boluses (2x)",
"Preserving Boluses (2x)",
"Neutralizing Boluses (2x)",
"Clarifying Boluses (2x)",
"Thawfrost Boluses (2x)",
"Spellproof Dried Liver",
"Lightningproof Dried Liver",
"Holyproof Dried Liver",
"Fireproof Dried Liver",
"Exalted Flesh",
"Pickled Turtle Neck (2x)",
"Cuckoo Glintstone (2x)",
"Frenzyflame Stone",
"Soap (3x)",
"Soft Cotton (3x)",
"Warming Stone (3x)",
"Hefty Fire Pot",
"Hefty Rock Pot",
"Hefty Lightning Pot",
"Hefty Fetid Pot",
"Hefty Fly Pot",
"Hefty Freezing Pot",
"Hefty Oil Pot",
"Hefty Volcano Pot",
"Hefty Frenzied Pot",
"Hefty Rancor Pot",
"Hefty Magic Pot",
"Hefty Rot Pot",
"Hefty Furnace Pot",
"Hefty Red Lightning Pot",
"Red Lightning Pot",
"Frenzied Flame Pot",
"Eternal Sleep Pot",
"Sunwarmth Stone Pot",
"Lulling Branch",
"Dragon Communion Flesh",
"Dragonscale Flesh",
"Fingerprint Nostrum",
"Spellproof Dried Liver (2x)",
"Fireproof Dried Liver (2x)",
"Lightningproof  Dried Liver (2x)",
"Holyproof Dried Liver (2x)",
"Spellproof Pickled Liver",
"Fireproof Pickled Liver",
"Lightningproof Pickled Liver",
"Holyproof Pickled Liver",
"Opaline Pickled Liver",
"Well-Pickled Turtle Neck"
];

uncraftablesList = [
"Boiled Prawn (2x)",
"Boiled Crab",
"Raw Meat Dumpling",
"Throwing Dagger (5x)",
"Kukri (3x) ",
"Fan Daggers (3x)",
"Poisoned Stone (3x)",
"Poisoned Stone Clump (2x)",
"Explosive Stone (3x) ",
"Explosive Stone Clump (2x)",
"Gravity Stone Chunk (3x)",
"Gravity Stone Fan (2x)",
"Glintstone Scrap (5x) ",
"Large Glintstone Scrap (2x)",
"Starlight Shard"
]

craftingMaterialsList = [
"Aeonian Butterfly",
"Albinauric Bloodclot",
"Altus Bloom (3x)",
"Arteria Leaf",
"Beast Blood",
"Beast Liver",
"Blood-Tainted Excrement",
"Bloodrose",
"Budding Cave Moss",
"Budding Horn",
"Cave Moss (2x)",
"Crab Eggs",
"Cracked Crystal (3x)",
"Crystal Bud",
"Crystal Cave Moss",
"Dewkissed Herba",
"Erdleaf Flower (3x)",
"Eye of Yelough",
"Faded Erdleaf Flower (3x)",
"Fire Blossom",
"Flight Pinion",
"Formic Rock",
"Fulgurbloom",
"Glintstone Firefly",
"Gold Firefly",
"Gold-Tinged Excrement",
"Golden Centipede",
"Golden Rowa",
"Golden Sunflower",
"Grave Violet",
"Gravel Stone",
"Great Dragonfly Head",
"Hefty Beast Bone",
"Herba (3x)",
"Human Bone Shard",
"Land Octopus Ovary",
"Living Jar Shard",
"Lump of Flesh",
"Melted Mushroom",
"Miquella's Lily",
"Miranda Powder",
"Mushroom (5x)",
"Nascent Butterfly",
"Old Fang",
"Poisonbloom",
"Rimed Crystal Bud",
"Root Resin",
"Rowa Fruit (x5)",
"Ruin Fragment (5x)",
"Sacramental Bud",
"Sanctuary Stone (2x)",
"Silver Firefly",
"Silver Tear Husk",
"Sliver of Meat",
"Slumbering Egg",
"Smoldering Butterfly (2x)",
"Stormhawk Feather",
"String (2x)",
"Strip of White Flesh",
"Tarnished Golden Sunflower",
"Thin Beast Bones (3x)",
"Toxic Mushroom",
"Trina's Lily",
"Turtle Neck Meat",
"Volcanic Stone",
"Yellow Ember",
"Spiritgrave Stone",
"Gas Stone (2x)",
"Nailstone (2x)",
"Sharp Gravel Stone",
"Rauh Burrow",
"Furnace Visage",
"Dewgem",
"Redflesh Mushroom",
"Whiteflesh Mushroom",
"Finger Mimic",
"Yellow Fulgurbloom",
"Red Fulgurbloom",
"Ghostflame Bloom",
"Shadow Sunflower",
"Scarlet Bud",
"Sanguine Amaryllis",
"Dragon's Calorbloom",
"Deep-Purple Lily",
"Nectarblood Burgeon",
"Empyrean-Blood Burgeon",
"Knot Resin (2x)",
"Beast Horn (2x)",
"Spirit Calculus",
"Scorpion Liver",
"Fly Mold (2x)",
"Pearlescent Scale",
"Ember of Messmer",
"Black Pyrefly",
"Glintslab Firefly",
"Toxic Mossling",
"Frozen Maggot",
"Winter-Lantern Fly",
"Grave Cricket",
"Grave Keeper's Brainpan",
"Congealed Putrescence",
"Blessed Bone Shard",
"Horn-Strewn Excrement",
"Swollen Grape"
]

weaponsList = [
"Omen Bairn",
"Wraith Calling Bell",
"Ancestral Infant's Head",
"Broadsword",
"Cane Sword",
"Carian Knight's Sword",
"Coded Sword",
"Crystal Sword",
"Golden Epitaph",
"Lazuli Glintstone Sword",
"Longsword",
"Lordsworn's Straight Sword",
"Miquellan Knight's Sword",
"Noble's Slender Sword",
"Ornamental Straight Sword",
"Regalia of Eochaid",
"Rotten Crystal Sword",
"Short Sword",
"Sword of Night and Flame",
"Sword of St Trina",
"Warhawk's Talon",
"Weathered Straight Sword",
"Bandit's Curved Sword",
"Beastman's Curved Sword",
"Eclipse Shotel",
"Falchion",
"Flowing Curved Sword",
"Grossmesser",
"Magma Blade",
"Mantis Blade",
"Nox Flowing Sword",
"Scavenger's Curved Sword",
"Scimitar",
"Serpent-God's Curved Sword",
"Shamshir",
"Shotel",
"Wing of Astel",
"Alabaster Lord's Sword",
"Banished Knight's Greatsword",
"Bastard Sword",
"Claymore",
"Death's Poker",
"Flamberge",
"Forked Greatsword",
"Gargoyle's Blackblade",
"Gargoyle's Greatsword",
"Golden Order Greatsword",
"Helphen's Steeple",
"Inseparable Sword",
"Iron Greatsword",
"Knight's Greatsword",
"Lordsworn's Greatsword",
"Marais Executioner's Sword",
"Ordovis's Greatsword",
"Sacred Relic Sword",
"Sword of Milos",
"Beastman's Cleaver",
"Bloodhound's Fang",
"Dismounter",
"Magma Wyrm's Scalesword",
"Monk's Flameblade",
"Omen Cleaver",
"Onyx Lord's Greatsword",
"Zamor Curved Sword",
"Dragon Greatclaw",
"Godslayer's Greatsword",
"Grafted Blade Greatsword",
"Greatsword",
"Maliketh's Black Blade",
"Royal Greatsword",
"Starscourge Greatsword",
"Troll Knight's Sword",
"Troll's Golden Sword",
"Watchdog's Greatsword",
"Zweihander",
"Axe of Godfrey",
"Duelist Greataxe",
"Envoy's Greathorn",
"Fallingstar Beast Jaw",
"Ghiza's Wheel",
"Golem's Halberd",
"Great Club",
"Prelate's Inferno Crozier",
"Rotten Greataxe",
"Rotten Staff",
"Staff of the Avatar",
"Troll's Hammer",
"Watchdog's Staff",
"Cleanrot Knight's Sword",
"Estoc",
"Frozen Needle",
"Noble's Estoc",
"Rapier",
"Rogier's Rapier",
"Bloody Helice",
"Dragon King's Cragblade",
"Godskin Stitcher",
"Great Epee",
"Dragonscale Blade",
"Meteoric Ore Blade",
"Nagakiba",
"Serpentbone Blade",
"Uchigatana",
"Battle Axe",
"Celebrant's Cleaver",
"Forked Hatchet",
"Hand Axe",
"Highland Axe",
"Icerind Hatchet",
"Iron Cleaver",
"Jawbone Axe",
"Ripple Blade",
"Rosus' Axe",
"Sacrificial Axe",
"Stormhawk Axe",
"Warped Axe",
"Axe of Godrick",
"Crescent Moon Axe",
"Executioner's Greataxe",
"Gargoyle's Black Axe",
"Gargoyle's Great Axe",
"Great Omenkiller Cleaver",
"Greataxe",
"Longhaft Axe",
"Rusted Anchor",
"Sacred Butchering Knife",
"Winged Greathorn",
"Black Knife",
"Blade of Calling",
"Bloodstained Dagger",
"Celebrant's Sickle",
"Cinquedea",
"Crystal Knife",
"Dagger",
"Erdsteel Dagger",
"Glintstone Kris",
"Great Knife",
"Ivory Sickle",
"Misericorde",
"Parrying Dagger",
"Reduvia",
"Wakizashi",
"Bolt of Gransax",
"Celebrant's Rib-Rake",
"Clayman's Harpoon",
"Cleanrot Spear",
"Cross-Naginata",
"Crystal Spear",
"Death Ritual Spear",
"Inquisitor's Girandole",
"Iron Spear",
"Partisan",
"Pike",
"Rotten Crystal Spear",
"Short Spear",
"Spear",
"Spiked Spear",
"Torchpole",
"Banished Knight's Halberd",
"Commander's Standard",
"Dragon Halberd",
"Gargoyle's Black Halberd",
"Gargoyle's Halberd",
"Glaive",
"Golden Halberd",
"Guardian's Swordspear",
"Halberd",
"Loretta's War Sickle",
"Lucerne",
"Nightrider Glaive",
"Pest's Glaive",
"Ripple Crescent Halberd",
"Vulgar Militia Saw",
"Vulgar Militia Shotel",
"Lance",
"Mohgwyn's Sacred Spear",
"Serpent-Hunter",
"Siluria's Tree",
"Treespear",
"Vyke's War Spear",
"Grave Scythe",
"Halo Scythe",
"Scythe",
"Winged Scythe",
"Eleonora's Poleblade",
"Gargoyle's Black Blades",
"Gargoyle's Twinblade",
"Godskin Peeler",
"Twinblade",
"Twinned Knight Swords",
"Club",
"Curved Club",
"Envoy's Horn",
"Hammer",
"Mace",
"Marika's Hammer",
"Monk's Flamemace",
"Morning Star",
"Nox Flowing Hammer",
"Ringed Finger",
"Scepter of the All-Knowing",
"Spiked Club",
"Varre's Bouquet",
"Warpick",
"Stone Club",
"Battle Hammer",
"Beastclaw Greathammer",
"Brick Hammer",
"Celebrant's Skull",
"Cranial Vessel Candlestand",
"Curved Great Club",
"Devourer's Scepter",
"Envoy's Long Horn",
"Great Mace",
"Great Stars",
"Greathorn Hammer",
"Large Club",
"Pickaxe",
"Rotten Battle Hammer",
"Bastard's Stars",
"Chainlink Flail",
"Family Heads",
"Flail",
"Nightrider Flail",
"Bloodhound Claws",
"Hookclaws",
"Raptor Talons",
"Venomous Fang",
"Caestus",
"Cipher Pata",
"Clinging Bone",
"Grafted Dragon",
"Iron Ball",
"Katar",
"Spiked Caestus",
"Star Fist",
"Veteran's Prosthesis",
"Giant's Red Braid",
"Hoslow's Petal Whip",
"Magma Whip Candlestick",
"Thorned Whip",
"Urumi",
"Whip",
"Albinauric Bow",
"Black Bow",
"Erdtree Bow",
"Horn Bow",
"Longbow",
"Pulley Bow",
"Serpent Bow",
"Light Bows",
"Composite Bow",
"Harp Bow",
"Misbegotten Shortbow",
"Red Branch Shortbow",
"Shortbow",
"Erdtree Greatbow",
"Golem Greatbow",
"Greatbow",
"Lion Greatbow",
"Arbalest",
"Crepus's Black-Key Crossbow",
"Full Moon Crossbow",
"Heavy Crossbow",
"Light Crossbow",
"Pulley Crossbow",
"Soldier's Crossbow",
"Hand Ballista",
"Jar Cannon",
"Beast-Repellent Torch",
"Ghostflame Torch",
"St Trina's Torch",
"Sentry's Torch",
"Steel-Wire Torch",
"Torch",
"Man-serpent's Shield",
"Rickety Shield",
"Pillory Shield",
"Beastman's Jar-shield",
"Red Thorn Roundshield",
"Scripture Wooden Shield",
"Riveted Wooden Shield",
"Blue-white Wooden Shield",
"Rift Shield",
"Iron Roundshield",
"Gilded Iron Shield",
"Ice Crest Shield",
"Smoldering Shield",
"Spiralhorn Shield",
"Coil Shield",
"Kite Shield",
"Marred Leather Shield",
"Marred Wooden Shield",
"Banished Knight's Shield",
"Albinauric Shield",
"Sun Realm Shield",
"Silver Mirrorshield",
"Round Shield",
"Scorpion Kite Shield",
"Twinbird Kite Shield",
"Blue-gold Kite Shield",
"Brass Shield",
"Great Turtle Shell",
"Shield Of The Guilty",
"Carian Knight's Shield",
"Large Leather Shield",
"Horse Crest Wooden Shield",
"Candletree Wooden Shield",
"Flame Crest Wooden Shield",
"Hawk Crest Wooden Shield",
"Beast Crest Heater Shield",
"Red Crest Heater Shield",
"Blue Crest Heater Shield",
"Eclipse Crest Heater Shield",
"Inverted Hawk Heater Shield",
"Heater Shield",
"Black Leather Shield",
"Dragon Towershield",
"Distinguished Greatshield",
"Crucible Hornshield",
"Dragonclaw Shield",
"Briar Greatshield",
"Erdtree Greatshield",
"Golden Beast Crest Shield",
"Jellyfish Shield",
"Fingerprint Stone Shield",
"Icon Shield",
"One-eyed Shield",
"Visage Shield",
"Spiked Palisade Shield",
"Manor Towershield",
"Crossed-tree Towershield",
"Inverted Hawk Towershield",
"Ant's Skull Plate",
"Redmane Greatshield",
"Eclipse Crest Greatshield",
"Cuckoo Greatshield",
"Golden Greatshield",
"Gilded Greatshield",
"Haligtree Crest Greatshield",
"Wooden Greatshield",
"Lordsworn's Shield",
"Dueling Shield",
"Carian Thrusting Shield",
"Dryleaf Arts",
"Dane's Footwork",
"Smithscript Dagger",
"Backhand Blade",
"Smithscript Cirque",
"Curseblade's Cirque",
"Firespark Perfume Bottle",
"Chilling Perfume Bottle",
"Frenzyflame Perfume Bottle",
"Lightning Perfume Bottle",
"Deadly Poison Perfume Bottle",
"Red Bear's Claw",
"Beast Claw",
"Milady",
"Leda's Sword",
"Great Katana",
"Dragon-Hunter's Great Katana",
"Rakshasa's Great Katana",
"Main-gauche",
"Fire-Knight's Shortsword",
"Velvet Sword of St Trina",
"Stone-Sheathed Sword",
"Sword of Light",
"Sword of Darkness",
"Lizard Greatsword",
"Greatsword of Damnation",
"Greatsword of Solitude",
"Ancient Meteoric Ore Greatsword",
"Fire-Knight's Greatsword",
"Moonrithyll's Knight Sword",
"Carian Sorcery Sword",
"Queelign's Greatsword",
"Sword Lance",
"Spirit Sword",
"Falx",
"Dancing Blade of Ranah",
"Horned Warrior's Sword",
"Horned Warrior's Greatsword",
"Freyja's Greatsword",
"Star-Lined Sword",
"Sword of Night",
"Euporia",
"Black Steel Twinblade",
"Forked-Tongue Hatchet",
"Smithscript Axe",
"Messmer Soldier's Axe",
"Death Knight's Twin Axes",
"Putrescence Cleaver",
"Death Knight's Longhaft Axe",
"Bonny Butchering Knife",
"Flowerstone Gavel",
"Serpent Flail",
"Black Steel Greathammer",
"Smithscript Greathammer",
"Bloodfiend's Arm",
"Anvil Hammer",
"Devonia's Hammer",
"Shadow Sunflower Blossom",
"Gazing Finger",
"Smithscript Spear",
"Swift Spear",
"Bloodfiend's Fork",
"Bloodfiend's Sacred Spear",
"Messmer Soldier's Spear",
"Barbed Staff-Spear",
"Spirit Glaive",
"Poleblade of the Bud",
"Obsidian Lamina",
"Tooth Whip",
"Pata",
"Golem Fist",
"Madding Hand",
"Thiollier's Hidden Needle",
"Poisoned Hand",
"Claws of Night",
"Bone Bow",
"Ansbach's Longbow",
"Igon's Greatbow",
"Repeating Crossbow",
"Spread Crossbow",
"Rabbath's Cannon",
"Lamenting Visage",
"Nanaya's Torch",
"Smithscript Shield",
"Shield of Night",
"Golden Lion Shield",
"Serpent Crest Shield",
"Wolf Crest Shield",
"Messmer Soldier Shield",
"Verdigris Greatshield",
"Black Steel Greatshield",
"Any Staff",
"Any Seal"
]

talismansList = [
"Crimson Amber Medallion",
"Crimson Amber Medallion +1",
"Crimson Amber Medallion +2",
"Cerulean Amber Medallion",
"Cerulean Amber Medallion +1",
"Cerulean Amber Medallion +2",
"Viridian Amber Medallion",
"Viridian Amber Medallion +1",
"Viridian Amber Medallion +2",
"Arsenal Charm",
"Arsenal Charm +1",
"Erdtree's Favor",
"Erdtree's Favor +1",
"Radagon's Scarseal",
"Radagon's Soreseal",
"Starscourge Heirloom",
"Prosthesis-Wearer Heirloom",
"Stargazer Heirloom",
"Two Fingers Heirloom",
"Silver Scarab",
"Gold Scarab",
"Moon of Nokstella",
"Green Turtle Talisman",
"Stalwart Horn Charm",
"Stalwart Horn Charm +1",
"Stalwart Horn Charm +2",
"Immunizing Horn Charm",
"Immunizing Horn Charm +1",
"Immunizing Horn Charm +2",
"Clarifying Horn Charm",
"Clarifying Horn Charm +1",
"Clarifying Horn Charm +2",
"Prince of Death's Cyst",
"Prince of Death's Pustule",
"Mottled Necklace",
"Mottled Necklace +1",
"Mottled Necklace +2",
"Bull-Goat's Talisman",
"Marika's Scarseal",
"Marika's Soreseal",
"Warrior Jar Shard",
"Shard of Alexander",
"Millicent's Prosthesis",
"Magic Scorpion Charm",
"Lightning Scorpion Charm",
"Fire Scorpion Charm",
"Sacred Scorpion Charm",
"Red-Feathered Branchsword",
"Ritual Sword Talisman",
"Spear Talisman",
"Hammer Talisman",
"Winged Sword Insignia",
"Rotten Winged Sword Insignia",
"Dagger Talisman",
"Arrow's Reach Talisman",
"Blue Dancer Charm",
"Twinblade Talisman",
"Axe Talisman",
"Lance Talisman",
"Arrow's Sting Talisman",
"Lord of Blood's Exultation",
"Kindred of Rot's Exultation",
"Claw Talisman",
"Roar Medallion",
"Curved Sword Talisman",
"Companion Jar",
"Perfumer's Talisman",
"Graven-School Talisman",
"Graven-Mass Talisman",
"Faithful's Canvas Talisman",
"Flock's Canvas Talisman",
"Old Lord's Talisman",
"Radagon Icon",
"Primal Glintstone Blade",
"Godfrey Icon",
"Dragoncrest Shield Talisman",
"Dragoncrest Shield Talisman +1",
"Spelldrake Talisman",
"Spelldrake Talisman +1",
"Spelldrake Talisman +2",
"Flamedrake Talisman",
"Flamedrake Talisman +1",
"Flamedrake Talisman +2",
"Boltdrake Talisman",
"Boltdrake Talisman +1",
"Boltdrake Talisman +2",
"Haligdrake Talisman",
"Haligdrake Talisman +1",
"Haligdrake Talisman +2",
"Pearldrake Talisman",
"Pearldrake Talisman +1",
"Pearldrake Talisman +2",
"Crucible Scale Talisman",
"Crucible Feather Talisman",
"Blue-Feathered Branchsword",
"Talisman of Lord's Bestowal",
"Dried Bouquet",
"Ailment Talisman",
"Rellana's Cameo",
"Pearl Shield Talisman",
"Blade of Mercy",
"Smithing Talisman",
"St.Trina's Smile",
"Enraged Divine Beast",
"Two-Handed Sword Talisman",
"Sharpshot Talisman",
"Arrow's Soaring Sting Talisman",
"Shattered Stone Talisman",
"Talisman of the Dread",
"Beloved Stardust",
"Talisman of All Crucibles",
"Fine Crucible Feather Talisman",
"Ritual Shield Talisman",
"Greatshield Talisman",
"Crucible Knot Talisman",
"Crimson Seed Talisman",
"Cerulean Seed Talisman",
"Blessed Dew Talisman",
"Blessed Blue Dew Talisman",
"Retaliatory Crossed-Tree",
"Lacerating Crossed-Tree",
"Aged One's Exultation",
"Taker's Cameo",
"Godskin Swaddling Cloth",
"Assassin's Crimson Dagger",
"Assassin's Cerulean Dagger",
"Crepus's Vial",
"Concealing Veil",
"Carian Filigreed Crest",
"Longtail Cat Talisman",
"Shabriri's Woe",
"Ancestral Spirit's Horn",
"Furled Finger's Trick Mirror",
"Host's Trick Mirror",
"Verdigris Discus",
"Crusade Insignia",
"Two-Headed Turtle Talisman"
];

legendaryList = [
"Regal Omen Bairn",
"Scorpion's Stinger",
"Rivers of Blood",
"Moonveil",
"Hand of Malenia",
"Antspur Rapier",
"Giant-Crusher",
"Ruins Greatsword",
"Morgott's Cursed Sword",
"Dark Moon Greatsword",
"Blasphemous Blade",
"Crimson Amber Medallion +3",
"Cerulean Amber Medallion +3",
"Viridian Amber Medallion +3",
"Great-Jar's Arsenal",
"Dragoncrest Greatshield Talisman",
"Spelldrake Talisman +3",
"Flamedrake Talisman +3",
"Boltdrake Talisman +3",
"Golden Braid",
"Pearldrake Talisman +3",
"Erdtree's Favor +3",
"Mimic Veil",
"Rellana's Twin Blades",
"Greatsword of Radahn (Light)",
"Greatsword of Radahn (Lord)",
"Spear of the Impaler"
];

armorList = [
    ["Alberich Set", ["Alberich's Pointed Hat", "Alberich's Robe", "Alberich's Bracers", "Alberich's Trousers"]],
["Albinauric Set", ["Albinauric Mask", "Dirty Chainmail", "", ""]],
["All-Knowing Set", ["All-Knowing Helm", "All-Knowing Armor", "All-Knowing Gauntlets", "All-Knowing Greaves"]],
["Aristocrat Set", ["Aristocrat Headband", "Aristocrat Garb", "", "Aristocrat Boots"]],
["Noble Soldier Set", ["Aristocrat Hat", "Aristocrat Coat", "", ""]],
["", ["Divine Beast Head", "", "", ""]],
["Astrologer Set", ["Astrologer Hood", "Astrologer Robe", "Astrologer Gloves", "Astrologer Trousers"]],
["Bandit Set", ["Bandit Mask", "Bandit Garb", "Bandit Manchettes", "Bandit Boots"]],
["Banished Knight Set", ["Banished Knight Helm", "Banished Knight Armor", "Banished Knight Gauntlets", "Banished Knight Greaves"]],
["Battlemage Set", ["Haima Glintstone Crown", "Battlemage Robe", "Battlemage Manchettes", "Battlemage Legwraps"]],
["Beast Champion Set", ["Beast Champion Helm", "Beast Champion Armor", "Beast Champion Gauntlets", "Beast Champion Greaves"]],
["Black Knife Set", ["Black Knife Hood", "Black Knife Armor", "Black Knife Gauntlets", "Black Knife Greaves"]],
["Blackflame Monk Set", ["Blackflame Monk Hood", "Blackflame Monk Armor", "Blackflame Monk Gauntlets", "Blackflame Monk Greaves"]],
["Prisoner Set", ["Prisoner Iron Mask", "Prisoner Clothing", "", "Prisoner Trousers"]],
["Blackguard Set", ["Blackguard's Iron Mask", "Prisoner Clothing", "", "Prisoner Trousers"]],
["Blaidd Set", ["Black Wolf Mask", "Blaidd's Armor", "Blaidd's Gauntlets", "Blaidd's Greaves"]],
["Bloodhound Knight Set", ["Bloodhound Knight Helm", "Bloodhound Knight Armor", "Bloodhound Knight Gauntlets", "Bloodhound Knight Greaves"]],
["Bloodsoaked Set", ["Bloodsoaked Mask", "Official's Attire", "Bloodsoaked Manchettes", ""]],
["Blue Cloth Set", ["Blue Cloth Cowl", "Blue Cloth Vest", "Warrior Gauntlets", "Warrior Greaves"]],
["Blue Festive Set", ["Blue Festive Hood", "Blue Festive Garb", "", ""]],
["Blue Silver Mail Set", ["Blue Silver Mail Hood", "Blue Silver Mail Armor", "Blue Silver Bracelets", "Blue Silver Mail Skirt"]],
["Briar Set", ["Briar Helm", "Briar Armor", "Briar Gauntlets", "Briar Greaves"]],
["Bull-Goat Set", ["Bull-Goat Helm", "Bull-Goat Armor", "Bull-Goat Gauntlets", "Bull-Goat Greaves"]],
["Carian Knight Set", ["Carian Knight Helm", "Carian Knight Armor", "Carian Knight Gauntlets", "Carian Knight Greaves"]],
["", ["Cerulean Tear Scarab", "", "", ""]],
["Chain Set", ["Chain Coif", "Chain Armor", "Gauntlets", "Chain Leggings"]],
["Champion Set", ["Champion Headband", "Champion Pauldron", "Champion Bracers", "Champion Gaiters"]],
["Cleanrot Set", ["Cleanrot Helm", "Cleanrot Armor", "Cleanrot Gauntlets", "Cleanrot Greaves"]],
["Guilty Set", ["Guilty Hood", "Cloth Garb", "", "Cloth Trousers"]],
["Commoner Set", ["Commoner's Headband", "Commoner's (Simple) Garb", "", "Commoner's Shoes"]],
["Confessor Set", ["Confessor Hood", "Confessor Armor", "Confessor Gloves", "Confessor Boots"]],
["Consort Set", ["Consort's Mask", "Consort's Robe", "", "Consort's Trousers"]],
["Corhyn Set", ["", "Corhyn's Robe", "", ""]],
["Crucible Axe Set", ["Crucible Axe Helm", "Crucible Axe Armor", "Crucible Gauntlets", "Crucible Greaves"]],
["Crucible Tree Set", ["Crucible Tree Helm", "Crucible Tree Armor", "Crucible Gauntlets", "Crucible Greaves"]],
["Crucible Hammer Set", ["Crucible Hammer-Helm", "Crucible Tree Armor", "Crucible Gauntlets", "Crucible Greaves"]],
["Cuckoo Knight Set", ["Cuckoo Knight Helm", "Cuckoo Knight Armor", "Cuckoo Knight Gauntlets", "Cuckoo Knight Greaves"]],
["", ["", "Deathbed Dress", "", ""]],
["Depraved Perfumer Set", ["Depraved Perfumer Headscarf", "Depraved Perfumer Robe", "Depraved Perfumer Gloves", "Depraved Perfumer Trousers"]],
["Drake Knight Set", ["Drake Knight Helm", "Drake Knight Armor", "Drake Knight Gauntlets", "Drake Knight Greaves"]],
["Duelist Set", ["Duelist Helm", "Gravekeeper Cloak", "", "Duelist Greaves"]],
["Eccentric Set", ["Eccentric's Hood", "Eccentric's Armor", "Eccentric's Manchettes", "Eccentric's Breeches"]],
["Elden Lord Set", ["Elden Lord Crown", "Elden Lord Armor", "Elden Lord Bracers", "Elden Lord Greaves"]],
["Errant Sorcerer Set", ["Hierodas Glintstone Crown", "Errant Sorcerer Robe", "Errant Sorcerer Manchettes", "Errant Sorcerer Boots"]],
["Exile Set", ["Exile Hood", "Exile Armor", "Exile Gauntlets", "Exile Greaves"]],
["Morgott's Set", ["", "Fell Omen Cloak", "", ""]],
["Festive Set", ["Festive Hood", "Festive Garb", "", ""]],
["Fia Set", ["Fia's Hood", "Fia's Robe", "", ""]],
["Finger Maiden Set", ["Finger Maiden Fillet", "Finger Maiden Robe", "", "Finger Maiden Shoes"]],
["Fingerprint Set", ["Fingerprint Helm", "Fingerprint Armor", "Fingerprint Gauntlets", "Fingerprint Greaves"]],
["Fire Monk Set", ["Fire Monk Hood", "Fire Monk Armor", "Fire Monk Gauntlets", "Fire Monk Greaves"]],
["Fire Prelate Set", ["Fire Prelate Helm", "Fire Prelate Armor", "Fire Prelate Gauntlets", "Fire Prelate Greaves"]],
["Godrick Foot Soldier Set", ["Foot Soldier Cap", "Chain-Draped Tabard", "Foot Soldier Gauntlets", "Foot Soldier Greaves"]],
["Radahn Foot Soldier Set", ["Foot Soldier Helm", "Scarlet Tabard", "Foot Soldier Gauntlets", "Foot Soldier Greaves"]],
["Raya Lucarian Foot Soldier Set", ["Foot Soldier Helmet", "Foot Soldier Tabard", "Foot Soldier Gauntlets", "Foot Soldier Greaves"]],
["Leyndell Foot Soldier Set", ["Gilded Foot Soldier Cap", "Leather-Draped Tabard", "Foot Soldier Gauntlets", "Foot Soldier Greaves"]],
["Mausoleum Foot Soldiers Set", ["", "Bloodsoaked Tabard", "Foot Soldier Gauntlets", "Foot Soldier Greaves"]],
["Haligtree Foot Soldier Set", ["Sacred Crown Helm", "Ivory-Draped Tabard", "Foot Soldier Gauntlets", "Foot Soldier Greaves"]],
["Godrick Soldier Set", ["Godrick Soldier Helm", "Tree-and-Beast Surcoat", "Godrick Soldier Gauntlets", "Godrick Soldier Greaves"]],
["Raya Lucarian Soldier Set", ["Raya Lucarian Helm", "Cuckoo Surcoat", "Raya Lucarian Gauntlets", "Raya Lucarian Greaves"]],
["Haligtree Soldier Set", ["Haligtree Helm", "Haligtree Crest Surcoat", "Haligtree Gauntlets", "Haligtree Greaves"]],
["Radahn Soldier Set", ["Radahn Soldier Helm", "Redmane Surcoat", "Radahn Soldier Gauntlets", "Radahn Soldier Greaves"]],
["Leyndell Soldier Set", ["Leyndell Soldier Helm", "Erdtree Surcoat", "Leyndell Soldier Gauntlets", "Leyndell Soldier Greaves"]],
["Leyndell Knight Set", ["Leyndell Knight Helm", "Leyndell Knight Armor", "Leyndell Knight Gauntlets", "Leyndell Knight Greaves"]],
["Redmane Knight Set", ["Redmane Knight Helm", "Redmane Knight Armor", "Redmane Knight Gauntlets", "Redmane Knight Greaves"]],
["Godrick Knight Set", ["Godrick Knight Helm", "Godrick Knight Armor", "Godrick Knight Gauntlets", "Godrick Knight Greaves"]],
["", ["", "Eye Surcoat", "", ""]],
["", ["", "Tree Surcoat", "", ""]],
["Godskin Apostle Set", ["Godskin Apostle Hood", "Godskin Apostle Robe", "Godskin Apostle Bracelets", "Godskin Apostle Trousers"]],
["Godskin Noble Set", ["Godskin Noble Hood", "Godskin Noble Robe", "Godskin Noble Bracelets", "Godskin Noble Trousers"]],
["Ancestral Follower's Set", ["Great Horned Headband", "Fur Rainment", "", "Fur Leggings"]],
["Gelmir Knight Set", ["Gelmir Knight Helm", "Gelmir Knight Armor", "Gelmir Knight Gauntlets", "Gelmir Knight Greaves"]],
["Glintstone Set", ["Glintstone Scarab", "", "", ""]],
["Goldmask's Set", ["Radiant Gold Mask", "Goldmask's Rags", "Gold Bracelets", "Gold Waistwrap"]],
["Guardian Set", ["Guardian Mask", "Guardian Garb (Full Bloom)", "Guardian Bracers", "Guardian Greaves"]],
["Haligtree Knight Set", ["Haligtree Knight Helm", "Haligtree Knight Armor", "Haligtree Knight Gauntlets", "Haligtree Knight Greaves"]],
["High Page Set", ["High Page Hood", "High Page Clothes", "", ""]],
["Highwayman Set", ["Highwayman Hood", "Highwayman Cloth Armor", "Highwayman Gauntlets", ""]],
["Hoslow Set", ["Hoslow's Helm", "Hoslow's Armor", "Hoslow's Gauntlets", "Hoslow's Greaves"]],
["Diallos's Set", ["Diallos's Mask", "Hoslow's Armor", "Hoslow's Gauntlets", "Hoslow's Greaves"]],
["", ["Iji's Mirrorhelm", "", "", ""]],
["", ["Imp Head (Cat)", "", "", ""]],
["Iron Set", ["Iron Helmet", "Scale Armor", "Iron Gauntlets", "Leather Trousers"]],
["Ronin Set", ["Iron Kasa", "Ronin's Armor", "Ronin's Gauntlets", "Ronin's Greaves"]],
["Juvenile Scholar Set", ["Juvenile Scholar Cap", "Juvenile Scholar Robe", "", ""]],
["Kaiden Set", ["Kaiden Helm", "Kaiden Armor", "Kaiden Gauntlets", "Kaiden Trousers"]],
["Raya Lucaria Set", ["Karolos Glintstone Crown", "Raya Lucarian Robe", "Sorcerer Manchettes", "Sorcerer Leggings"]],
["Twinsage Sorcerer Set", ["Twinsage Glintstone Crown", "Raya Lucarian Robe", "Sorcerer Manchettes", "Sorcerer Leggings"]],
["Lazuli Set", ["Lazuli Glintstone Crown", "Lazuli Robe", "Sorcerer Manchettes", "Sorcerer Leggings"]],
["Azur Glintstone Set", ["Azur's Glintstone Crown", "Azur's Glintstone Robe", "Azur's Manchettes", "Old Sorcerer's Legwraps"]],
["Lusat Glintstone Set", ["Lusat's Glintstone Crown", "Lusat's Robe", "Lusat's Manchettes", "Old Sorcerer's Legwraps"]],
["Knight Set", ["Knight Helm", "Knight Armor", "Knight Gauntlets", "Knight Greaves"]],
["Land of Reeds Set", ["Land of Reeds Helm", "Land of Reeds Armor", "Land of Reeds Gauntlets", "Land of Reeds Greaves"]],
["Leather Set", ["Black Hood", "Leather Armor", "Leather Gloves", "Leather Boots"]],
["Lionel Set", ["Lionel's Helm", "Lionel's Armor", "Lionel's Gauntlets", "Lionel's Greaves"]],
["Roderika's Set", ["Crimson Hood", "Noble's Traveling Garb", "Noble's Gloves", "Noble's Trousers"]],
["Noble Set", ["Navy Hood", "Noble's Traveling Garb", "Noble's Gloves", "Noble's Trousers"]],
["Lord of Blood Set", ["Octopus Head", "Lord Blood's Robe", "", ""]],
["Malenia Set", ["Malenia's Winged Helm", "Malenia's Armor", "Malenia's Gauntlet", "Malenia's Greaves"]],
["Malformed Dragon Set", ["Malformed Dragon Helm", "Malformed Dragon Armor", "Malformed Dragon Gauntlets", "Malformed Dragon Greaves"]],
["Maliketh Set", ["Maliketh's Helm", "Maliketh's Armor", "Maliketh's Gauntlets", "Maliketh's Greaves"]],
["Marais Set", ["Marais Mask", "Marais Robe", "", ""]],
["Marionette Soldier Set", ["Marionette Soldier Helm", "Marionette Soldier Armor", "", ""]],
["Marionette Bird Set", ["Marionette Soldier Birdhelm", "Marionette Soldier Armor", "", ""]],
["Mausoleum Knight Set", ["", "Mausoleum Knight Armor", "Mausoleum Knight Gauntlets", "Mausoleum Knight Greaves"]],
["Mushroom Set", ["Mushroom Head", "Mushroom Body", "Mushroom Arms", "Mushroom Legs"]],
["Night's Cavalry Set", ["Night's Cavalry Helm", "Night's Cavalry Armor", "Night's Cavalry Gauntlets", "Night's Cavalry Greaves"]],
["Nomadic Merchant Set", ["Nomadic Merchant's Chapeau", "Nomadic Merchant's Finery", "", "Nomadic Merchant's Trousers"]],
["Nox Monk Set", ["Nox Monk Hood", "Nox Monk Armor", "Nox Gauntlets", "Nox Greaves"]],
["Night Maiden Set", ["Night Maiden Twin Crown", "Night Maiden Armor", "Nox Gauntlets", "Nox Greaves"]],
["Nox Swordstress Set", ["Nox Swordstress Crown", "Nox Swordstress Armor", "Nox Gauntlets", "Nox Greaves"]],
["White Reed Set", ["Okina Mask", "White Reed Armor", "White Reed Gauntlets", "White Reed Greaves"]],
["Old Aristocrat Set", ["Old Aristocrat Cowl", "Old Aristocrat Gown", "", "Old Aristocrat Shoes"]],
["Omen Set", ["Omen Helm", "Omen Armor", "Omen Gauntlets", "Omen Greaves"]],
["Omenkiller Set", ["Omensmirk Mask", "Omenkiller Robe", "Omenkiller Long Gloves", "Omenkiller Boots"]],
["Page Set", ["Page Hood", "Page Garb", "", "Page Trousers"]],
["Perfumer Set", ["Perfumer Hood", "Perfumer Robe", "Perfumer Gloves", "Perfumer Sarong"]],
["Perfumer's Traveling Set", ["Traveler's Hat", "PerfumerPerfumer's Traveling Garb", "Traveler's Gloves", "Traveler's Slops"]],
["Seluvis' Set", ["Preceptor's Big Hat", "Preceptor's Long Gown", "Preceptor's Gloves", "Preceptor's Trousers"]],
["Preceptor Miriam's Set", ["Mask of Confidence", "Preceptor's Long Gown", "Preceptor's Gloves", "Preceptor's Trousers"]],
["Prophet Set", ["Prophet Blindfold", "Prophet Robe", "", "Prophet Trousers"]],
["Queen Set", ["Queen's Crescent Crown", "Queen's Robe", "Queen's Bracelets", "Queen's Leggings"]],
["Radahn Set", ["Radahn's Redmane Helm", "Radahn's Lion Armor", "Radahn's Gauntlets", "Radahn's Greaves"]],
["Raging Wolf Set", ["Raging Wolf Helm", "Raging Wolf Armor", "Raging Wolf Gauntlets", "Raging Wolf Greaves"]],
["Raptor Set", ["Skeletal Mask", "Raptor's Black Feathers", "", ""]],
["Rotten Duelist Set", ["Rotten Duelist Helm", "Rotten Gravekeeper Cloak", "", "Rotten Duelist Greaves"]],
["Royal Knight Set", ["Royal Knight Helm", "Royal Knight Armor", "Royal Knight Gauntlets", "Royal Knight Greaves"]],
["Royal Remains Set", ["Royal Remains Helm", "Royal Remains Armor", "Royal Remains Gauntlets", "Royal Remains Greaves"]],
["Ruler Set", ["RulerRuler's Mask", "RulerRuler's Robe", "", ""]],
["Sage Set", ["Sage Hood", "Sage Robe", "", "Sage Trousers"]],
["Sanguine Noble Set", ["Sanguine Noble Hood", "Sanguine Noble Robe", "", "Sanguine Noble Waistcloth"]],
["Scaled Set", ["Scaled Helm", "Scaled Armor", "Scaled Gauntlets", "Scaled Greaves"]],
["Shaman Set", ["Shining Horned Headband", "Shaman Furs", "", "Shaman Leggings"]],
["", ["Silver Tear Mask", "", "", ""]],
["Snow Witch Set", ["Snow Witch Hat", "Snow Witch Robe", "", "Snow Witch Skirt"]],
["Spellblade Set", ["Spellblade's Pointed Hat", "Spellblade's Traveling Attire", "Spellblade's Gloves", "Spellblade's Trousers"]],
["Traveler Set", ["", "Traveler's Clothes", "Traveler's Manchettes", "Traveler's Boots"]],
["Traveling Maiden Set", ["Traveling Maiden Hood", "Traveling Maiden Robe", "Traveling Maiden Gloves", "Traveling Maiden Boots"]],
["Tree Sentinel Set", ["Tree Sentinel Helm", "Tree Sentinel Armor", "Tree Sentinel Gauntlets", "Tree Sentinel Greaves"]],
["Twinned Set", ["Twinned Helm", "Twinned Armor", "Twinned Gauntlets", "Twinned Greaves"]],
["Upper-Class Set", ["", "Upper-Class Robe", "", ""]],
["Vagabond Knight Set", ["Vagabond Knight Helm", "Vagabond Knight Armor", "Vagabond Knight Gauntlets", "Vagabond Knight Greaves"]],
["Veteran Set", ["Veteran's Helm", "Veteran's Armor", "Veteran's Gauntlets", "Veteran's Greaves"]],
["Vulgar Militia Set", ["Vulgar Militia Helm", "Vulgar Militia Armor", "Vulgar Militia Gauntlets", "Vulgar Militia Greaves"]],
["War Surgeon Set", ["White Mask", "War Surgeon Gown", "War Surgeon Gloves", "War Surgeon Trousers"]],
["", ["Witch's Glintstone Crown", "", "", ""]],
["Zamor Set", ["Zamor Mask", "Zamor Armor", "Zamor Bracelets", "Zamor Legwraps"]],
["Fire Knight Set", ["Fire Knight Helm", "Fire Knight Armor", "Fire Knight Gauntlets", "Fire Knight Greaves"]],
["Wego's Set", ["Death Mask Helm", "Fire Knight Armor", "Fire Knight Gauntlets", "Fire Knight Greaves"]],
["Salza's Set", ["Salza's Hood", "Fire Knight Armor", "Fire Knight Gauntlets", "Fire Knight Greaves"]],
["Kood's Set", ["Winged Serpent Helm", "Fire Knight Armor", "Fire Knight Gauntlets", "Fire Knight Greaves"]],
["Ansbach's Set", ["Wise Man's Mask", "Ansbach's Attire", "Ansbach's Manchettes", "Ansbach's Boots"]],
["Ascetic Set", ["Curseblade Mask", "Ascetic's Loincloth", "Ascetic's Wrist Guards", "Ascetic's Ankle Guards"]],
["Black Knight Set", ["Black Knight Helm", "Black Knight Armor", "Black Knight Gauntlets", "Black Knight Greaves"]],
["Common Soldier Set", ["Common Soldier Helm", "Common Soldier Cloth Armor", "Common Soldier Gauntlets", "Common Soldier Greaves"]],
["Dancer's Set", ["Dancer's Hood", "Dancer's Dress", "Dancer's Bracer", "Dancer's Trousers"]],
["Death Knight Set", ["Death Knight Helm", "Death Knight Armor", "Death Knight Gauntlets", "Death Knight Greaves"]],
["Divine Beast Set", ["Divine Beast Helm", "Divine Beast Warrior Armor", "", ""]],
["Divine Bird Set", ["Divine Bird Helm", "Divine Bird Warrior Armor", "Divine Bird Warrior Gauntlets", "Divine Bird Warrior Greaves"]],
["Dryleaf Set", ["Dane Dane's Hat", "Dryleaf Robe", "Dryleaf Arm Wraps", "Dryleaf Cuissardes"]],
["Freyja's Set", ["Freyja's Helm", "Freyja's Armor", "Freyja's Gauntlets", "Freyja's Greaves"]],
["Gaius's Set", ["Gaius's Helm", "Gaius's Armor", "Gaius's Gauntlets", "Gaius's Greaves"]],
["Gravebird Set", ["Gravebird Helm", "Gravebird Armor", "Gravebird Bracelets", "Gravebird Anklets"]],
["Gravebird Blackquill Set", ["Gravebird Helm", "Gravebird's Blackquill Armor", "Gravebird Bracelets", "Gravebird Anklets"]],
["High Priest Set", ["High Priest Hat", "High Priest Robe", "High Priest Gloves", "High Priest Undergarments"]],
["Highland Leather Set", ["Leather Crown", "Highland Attire", "Leather Arm Wraps", "Leather Leg Wraps"]],
["Horned Warrior Set", ["Horned Warrior Helm", "Horned Warrior Armor", "Horned Warrior Gauntlets", "Horned Warrior Greaves"]],
["Hornsent Set", ["Caterpillar Mask", "Braided Cord Robe", "Braided Arm Wraps", "Soiled Loincloth"]],
["Igon's Set", ["Igon's Helm", "Igon's Armor", "Igon's Gauntlets", "Igon's Loincloth"]],
["Iron Rivet Set", ["Fang Helm", "Iron Rivet Armor", "Iron Rivet Gauntlets", "Iron Rivet Greaves"]],
["Messmer Soldier Set", ["Messmer Soldier Helm", "Messmer Soldier Armor", "Messmer Soldier Gauntlets", "Messmer Soldier Greaves"]],
["Messmer's Set", ["Messmer's Helm", "Messmer's Armor", "Messmer's Gauntlets", "Messmer's Greaves"]],
["Night Set", ["Helm of Night", "Armor of Night", "Gauntlets of Night", "Greaves of Night"]],
["Oathseeker Knight Set", ["Oathseeker Knight Helm", "Oathseeker Knight Armor", "Oathseeker Knight Gauntlets", "Oathseeker Knight Greaves"]],
["Leda's Set", ["Oathseeker Knight Helm", "Led's Armor", "Oathseeker Knight Gauntlets", "Oathseeker Knight Greaves"]],
["Rakshasa Set", ["Rakshasa Helm", "Rakshasa Armor", "Rakshasa Gauntlets", "Rakshasa Greaves"]],
["Rellana's Set", ["Rellana's Helm", "Rellana's Armor", "Rellana's Gloves", "Rellana's Greaves"]],
["Shadow Militiaman Set", ["Shadow Militiaman Helm", "Shadow Militiaman Armor", "Shadow Militiaman Gauntlets", "Shadow Militiaman Greaves"]],
["Solitude Set", ["Helm of Solitude", "Armor of Solitude", "Gauntlets of Solitude", "Greaves of Solitude"]],
["Thiollier's Set", ["Thiollier's Mask", "Thiollier's Garb", "Thiollier's Gloves", "Thiollier's Trousers"]],
["Verdigris Set", ["Verdigris Helm", "Verdigris Armor", "Verdigris Gauntlets", "Verdigris Greaves"]],
["Young Lion's Set", ["Young Lion's Helm", "Young Lion's Armor", "Young Lion's Gauntlets", "Young Lion's Greaves"]]
];

miracleList = [
"Agheel's Flame",
"Ancient Dragons' Lightning Spear",
"Ancient Dragons' Lightning Strike",
"Aspect of the Crucible: Breath",
"Aspect of the Crucible: Horns",
"Aspects of the Crucible: Tail",
"Assassin's Approach",
"Barrier of Gold",
"Beast Claw",
"Bestial Constitution",
"Bestial Sling",
"Bestial Vitality",
"Black Blade",
"Black Flame",
"Black Flame Blade",
"Black Flame Ritual",
"Black Flame's Protection",
"Blessing of the Erdtree",
"Blessing's Boon",
"Bloodboon",
"Bloodflame Blade",
"Bloodflame Talons",
"Borealis's Mist",
"Burn, O Flame!",
"Catch Flame",
"Cure Poison",
"Darkness",
"Death Lightning",
"Discus of Light",
"Divine Fortification",
"Dragonbolt Blessing",
"Dragonclaw",
"Dragonfire",
"Dragonice",
"Dragonmaw",
"Ekzykes's Decay",
"Elden Stars",
"Electrify Armament",
"Erdtree Heal",
"Fire's Deadly Sin",
"Flame Fortification",
"Flame Sling",
"Flame of the Fell God",
"Flame, Cleanse Me",
"Flame, Fall Upon Them",
"Flame, Grant me Strength",
"Flame, Protect Me",
"Fortissax's Lightning Spear",
"Frenzied Burst",
"Frozen Lightning Spear",
"Giantsflame Take Thee",
"Glintstone Breath",
"Golden Lightning Fortification",
"Golden Vow",
"Great Heal",
"Greyoll's Roar",
"Gurrang's Beast Claw",
"Heal",
"Honed Bolt",
"Howl of Shabriri",
"Immutable Shield",
"Inescapable Frenzy",
"Lansseax's Glaive",
"Law of Causality",
"Law of Regression",
"Lightning Fortification",
"Lightning Spear",
"Lightning Strike",
"Litany of Proper Death",
"Lord's Aid",
"Lord's Divine Fortification",
"Lord's Heal",
"Magic Fortification",
"Magma Breath",
"Noble Presence",
"O, Flame!",
"Order Healing",
"Order's Blade",
"Pest Threads",
"Placidusax's Ruin",
"Poison Armament",
"Poison Mist",
"Protection of the Erdtree",
"Radagon's Rings of Light",
"Rejection",
"Rotten Breath",
"Scarlet Aeonia",
"Scouring Black Flame",
"Shadow Bait",
"Smarag's Glintstone Breath",
"Stone of Gurranq",
"Surge, O Flame!",
"Swarm of Flies",
"The Flame of Frenzy",
"Theodorix's Magma",
"Triple Rings of Light",
"Unendurable Frenzy",
"Urgent Heal",
"Vyke's Dragonbolt",
"Whirl, O Flame!",
"Wrath of Gold",
"Furious Blade of Ansbach",
"Heal From Afar",
"Aspects of the Crucible: Thorns",
"Aspects of the Crucible: Bloom",
"Minor Erdtree",
"Lands of Shadow",
"Wrath From Afar",
"Light of Miquella",
"Multilayered Ring of Light",
"Roar of Rugalea",
"Knight's Lightning Spear",
"Dragonbolt of Florissax",
"Electrocharge",
"Bayle's Tyranny",
"Bayle's Flame Lightning",
"Ghostflame Breath",
"Rotten Butterflies",
"Pest-Thread Spears",
"Midra's Flame of Frenzy",
"Divine Beast Tornado",
"Divine Bird Feathers",
"Fire Serpent",
"Rain of Fire",
"Messmer's Orb",
"Watchful Spirit",
"Golden Arcs",
"Giant Golden Arc",
"Spira"
];

spellList = [
"Adula's Moonblade",
"Ambush Shard",
"Ancient Death of Rancor",
"Briars of Punishment",
"Briars of Sin",
"Cannon of Haima",
"Carian Greatsword",
"Carian Phalanx",
"Carian Piercer",
"Carian Retaliation",
"Carian Slicer",
"Collapsing Stars",
"Comet",
"Comet Azur",
"Crystal Barrage",
"Crystal Burst",
"Crystal Release",
"Crystal Torrent",
"Eternal Darkness",
"Explosive Ghostflame",
"Fia's Mist",
"Founding Rain of Stars",
"Freezing Mist",
"Frozen Armament",
"Gavel of Haima",
"Gelmir's Fury",
"Glintblade Phalanx",
"Glintstone Arc",
"Glintstone Cometshard",
"Glintstone Icecrag",
"Glintstone Pebble",
"Glintstone Stars",
"Gravity Well",
"Great Glintstone Shard",
"Great Oracular Bubble",
"Greatblade Phalanx",
"Loretta's Greatbow",
"Loretta's Mastery",
"Lucidity",
"Magic Bubble",
"Magic Downpour",
"Magic Glintblade",
"Magma Shot",
"Meteorite",
"Meteorite of Astel",
"Night Comet",
"Night Maiden's Mist",
"Night Shard",
"Oracle Bubbles",
"Rancorcall",
"Ranni's Dark Moon",
"Rennala's Full Moon",
"Rock Blaster",
"Rock Sling",
"Roiling Magma",
"Rykard's Rancor",
"Scholar's Armament",
"Scholar's Shield",
"Shard Spiral",
"Shatter Earth",
"Shatterlng Crystal",
"Star Shower",
"Starlight",
"Stars of Ruin",
"Swift Glintstone Shard",
"Terra Magicus",
"Thops's Barrier",
"Tibia's Summons",
"Unseen Blade",
"Unseen Form",
"Zamor Ice Storm",
"Miriam's Vanishing",
"Glintblade Trio",
"Rellana's Twin Moons",
"Glintstone Nail",
"Glintstone Nails",
"Blades of Stone",
"Gravitational Missile",
"Mantle of Thorns",
"Impenetrable Thorns",
"Rings of Spectral Light",
"Vortex of Putrescence",
"Mass of Putrescence",
"Fleeting Microcosm",
"Cherishing Fingers"
];

ashOfWarList = [
"Ash of War: Stamp (Upward Cut)",
"Ash of War: Stamp (Sweep)",
"Ash of War: Wild Strikes",
"Ash of War: Lion's Claw",
"Ash of War: Cragblade",
"Ash of War: Kick",
"Ash of War: Endure",
"Ash of War: Ground Slam",
"Ash of War: Earthshaker",
"Ash of War: Hoarah Loux's Earthshaker",
"Ash of War: War Cry",
"Ash of War: Barbaric Roar",
"Ash of War: Braggart's Roar",
"Ash of War: Troll's Roar",
"Ash of War: Spinning Slash",
"Ash of War: Impaling Thrust",
"Ash of War: Piercing Fang",
"Ash of War: Repeating Thrust",
"Ash of War: Double Slash",
"Ash of War: Sword Dance",
"Ash of War: Unsheathe",
"Ash of War: Quickstep",
"Ash of War: Bloodhound's Step",
"Ash of War: Raptor of the Mists",
"Ash of War: Beast's Roar",
"Ash of War: Square Off",
"Ash of War: Charge Forth",
"Ash of War: Spinning Strikes",
"Ash of War: Giant Hunt",
"Ash of War: Storm Blade",
"Ash of War: Storm Assault",
"Ash of War: Stormcaller",
"Ash of War: Storm Stomp",
"Ash of War: Vacuum Slice",
"Ash of War: Phantom Slash",
"Ash of War: Determination",
"Ash of War: Royal Knight's Resolve",
"Ash of War: Glintstone Pebble",
"Ash of War: Glintblade Phalanx",
"Ash of War: Carian Greatsword",
"Ash of War: Carian Grandeur",
"Ash of War: Spinning Weapon",
"Ash of War: Loretta's Slash",
"Ash of War: Gravitas",
"Ash of War: Waves of Darkness",
"Ash of War: Flaming Strike",
"Ash of War: Flame of the Redmanes",
"Ash of War: Eruption",
"Ash of War: Prelate's Charge",
"Ash of War: Black Flame Tornado",
"Ash of War: Thunderbolt",
"Ash of War: Lightning Slash",
"Ash of War: Lightning Ram",
"Ash of War: Sacred Blade",
"Ash of War: Prayerful Strike",
"Ash of War: Sacred Ring of Light",
"Ash of War: Sacred Order",
"Ash of War: Shared Order",
"Ash of War: Golden Land",
"Ash of War: Golden Slam",
"Ash of War: Golden Vow",
"Ash of War: Vow of the Indomitable",
"Ash of War: Holy Ground",
"Ash of War: Poisonous Mist",
"Ash of War: Poison Moth Flight",
"Ash of War: Blood Blade",
"Ash of War: Bloody Slash",
"Ash of War: Blood Tax",
"Ash of War: Seppuku",
"Ash of War: Ice Spear",
"Ash of War: Chilling Mist",
"Ash of War: Hoarfrost Stomp",
"Ash of War: Spectral Lance",
"Ash of War: Lifesteal Fist",
"Ash of War: White Shadow's Lure",
"Ash of War: Assassin's Gambit",
"Ash of War: Mighty Shot",
"Ash of War: Through and Through",
"Ash of War: Barrage",
"Ash of War: Sky Shot",
"Ash of War: Enchanted Shot",
"Ash of War: Rain of Arrows",
"Ash of War: Parry",
"Ash of War: Golden Parry",
"Ash of War: Storm Wall",
"Ash of War: Shield Bash",
"Ash of War: Shield Crash",
"Ash of War: Barricade Shield",
"Ash of War: Thops's Barrier",
"Ash of War: Carian Retaliation",
"Ash of War: No Skill",
"Ash of War: Dryleaf Whirlwind",
"Ash of War: Aspects of the Crucible: Wings",
"Ash of War: Spinning Gravity Thrust",
"Ash of War: Palm Blast",
"Ash of War: Piercing Throw",
"Ash of War: Scattershot Throw",
"Ash of War: Wall of Sparks",
"Ash of War: Rolling Sparks",
"Ash of War: Raging Beast",
"Ash of War: Savage Claws",
"Ash of War: Blind Spot",
"Ash of War: Swift Slash",
"Ash of War: Overhead Stance",
"Ash of War: Wing Stance",
"Ash of War: Blinkbolt",
"Ash of War: Flame Skewer",
"Ash of War: Savage Lion's Claw",
"Ash of War: Divine Beast Frost Stomp",
"Ash of War: Flame Spear",
"Ash of War: Carian Sovereignty",
"Ash of War: Shriek of Sorrow",
"Ash of War: Ghostflame Call",
"Ash of War: The Poison Flower Blooms Twice",
"Ash of War: Igon's Drake Hunt",
"Ash of War: Shield Strike"
]


misfortuneList = [
//Format: Whole text, effect text, number of turns
["Right Hand 1 broken. Stash the item in the slot.",  "Stash RH1", 1],
["Right Hand 1 broken. Stash the item in the slot.", "Stash RH1", 1],
["Right Hand 2 broken. Stash the item in the slot.", "Stash RH2", 1],
["Right Hand 2 broken. Stash the item in the slot.", "Stash RH2", 1],
["Right Hand 3 broken. Stash the item in the slot.", "Stash RH3", 1],
["Left Hand 1 broken. Stash the item in the slot.", "Stash LH1", 1],
["Left Hand 1 broken. Stash the item in the slot.", "Stash LH1", 1],
["Left Hand 2 broken. Stash the item in the slot.", "Stash LH2", 1],
["Left Hand 2 broken. Stash the item in the slot.", "Stash LH2", 1],
["Left Hand 3 broken. Stash the item in the slot.", "Stash LH3", 1],
["Your helmet broke. Stash the item in the slot.", "Stash helmet", 1],
["Your chestplate broke. Stash the item in the slot.", "Stash chestplate", 1],
["Your leggings broke. Stash the item in the slot.", "Stash leggings", 1],
["Your gauntlets broke. Stash the item in the slot.", "Stash gauntlets", 1],
["Your helmet broke. Stash the item in the slot.", "Stash helmet", 1],
["Your chestplate broke. Stash the item in the slot.", "Stash chestplate", 1],
["Your leggings broke. Stash the item in the slot.", "Stash leggings", 1],
["Your gauntlets broke. Stash the item in the slot.", "Stash gauntlets", 1],
["Unequip your pants and leave the slot free.. Giggity.", "Empty leg slot", 1],
["Unequip your chestpiece and leave the slot free. Time to get schwifty.", "Empty chest slot", 1],
["Unequip your gloves and leave the slot free. Bare hands bear hands.", "Empty gauntlet slot", 1],
["You have been cursed with the daedicars effect for the next match. Equip the Daedicar talisman.", "Daedicar effect", 1],
["You have been cursed with the daedicars effect for the next match. Equip the Daedicar talisman.", "Daedicar effect", 1],
["You have been daedicar'd for the next 3 matches. Equip the daedicar's woe", "Daedicar effect", 3],
["Poor guy. Your entire armor broke. Stash every armor piece equipped", "", 0],
["Poor guy... Your entire left hand set suddenly broke. Stash every left hand item equipped.", "", 0],
["Poor guy... Your entire right hand set suddenly broke. Stash every right hand item.", "", 0]
["Unequip 1 of your weapons. That slot cannot be occupied until after the match.", "Empty one slot and leave it free", 1],
["Unequip 1 of your armor pieces. Slot must be free for next match.", "Empty one armor slot and leave it free", 1],
["Unequip 1 of your talismans. Slot must be free for next match.", "Empty one talismans slot and leave it free", 1],
["Unequip 1 of any of your equipment slots. Slot must be free for next match.", "Empty one slot and leave it free", 1],
["Parrying is out of the question for the next match.", "No parrying", 1],
["Sexy time. Unequip pants for next match.", "Leg slot must be free", 1],
["Cut of yer 'ead. Remove helmet and the helmet slot must stay empty next match", "Helmet slot must stay empty", 1],
["Unequip all rings. You can reequip them after next match. (Daedicar's stays on if active.)", "Leave ring slots free", 1]
];

challengeList = [
//Format: Whole text, effect text, number of turns
["Rolling is only possible with an empty active left hand slot for next match", "Challenge: Left hand empty roll only", 1],
["Rolling is only possible with an empty active right hand slot for next match", "Challenge: Right hand empty roll only", 1],
["No rolls mode. Backstep and jumping is fine.", "Challenge: No roll", 1],
["Cheeky gesture on every kill in the next match. Even when there's enemies alive.", "Challenge: Gesture on enemy kill", 1],
["No lock on next match.", "Challenge: No lock jock", 1],
["Blocking is a no-no for next match. Parrying is Ok, Partials are also OK.", "Challenge: No block jock", 1],
["Your right hand needs to be empty for next match. You can two hand your left hand weapon.", "Challenge: No right hand weapons", 1],
["You need to fight with 70%+ equip load next match.", "Challenge: Bull Goat Buffoon", 1],
["Swap every right hand slot item with the according left hand slot item (r1 with l1, etc...). You are not allowed to two-hand your left hand items.", "Challenge: Left hand mode", 1],
["Parry at least once in this round, and before you riposte, you have to spin around twice.", "Challenge: The spinposte", 1],
["If you manage to make your enemy do a cheeky gesture at you (or teabag you), whether you are alive or dead, you get +2 rolls.", "Challenge: Piss off enemy", 1],
["Humiliate your enemy. The final hit on any kill needs to be a critical attack.", "Challenge: Humiliation", 1],
["You can't input anything until you've been hit once, starting from the moment the enemy spawns. You are allowed to communicate with emotes, however.", "Challenge: Controller disconnected", 1],
["You are now samurai. Equip any reeds' or white reed's set you have (and leave those you don't have empty). If you have a katana with unsheathe, use it. ", "Challenge: Honorable Samurai", 1],
["You have to press right d-pad every time you hit the enemy with your weapon even once.", "Challenge: The Jack Of No Trades", 1],
["Light roll time. You have to fight with under 30% equip load.", "Challenge: The Butterfly", 1],
["After the first action on an enemy you can't let your stamina regen to full, ever, until at least one enemy is dead.", "Challenge: Beserk", 1],
["Fucked paired weapons mode. Equip a different category of offensive melee weapon in each hand and hit at least once with both of them.", "Challenge: Depower stance", 1],
["Equip any soldier or knight helmet, and no chestplate. You have to run or walk at the enemy the entire time, you cannot retreat, until the match is over.", "Challenge: No fear", 1],
["You have to fight naked. Leave every armor slot free.", "Challenge: The Naked Man", 1],
["You have to hold B (or running button) the entire time. No releasing. Pretend it's glued shut.", "Challenge: B button stuck", 1],
["You have to use 5 buff consumables or spells before the fighting starts. You can't attack anything until you have.", "The duelist", 1],
["Equip any soldier or knight helmet, and no chestplate. If possible, equip a fist weapon and kill your enemy with it.", "The buff bitch", 1],
["You can only deal damage when your feet are off the ground.", "The Jumpman", 1]
];

tutorial = "Welcome to Rags to Riches!\nThis is a challenge type for Elden Ring PVP in which you rise from poor peasant to Ruin Greatsword-wielding menace by winning matches.\n\nThe Setup:\n1. Have a character with (ideally) all items in the game, and stash them all, except for: \n2. Start with the Commoners Set + Shortsword + Rickety Shield with no talismans\n3. Stats, infusions on weapons are all your choice\n\nThe Routine:\n1. Equip your character from everything you have in your inventory\n2. Begin a colosseum match or an invasion\n3. Fight with your pre-equipped stuff and the challenges that are currently active \n4. Every kill / round won nets you a click on 'Win', every death means one click on 'Lose'.\n5. See your amount of rewards and click the buttons, add rewarded items from the storage to your inventory. Do what it says on misfortunes.\n6. You can decide for yourself if you can change your equipment while in an invasion or undead match, but switching with D-Pad is always fine.\n7. In between rounds you can visit go the Roundtable and change Affinities, upgrade and change stuff around.\n\nWord meanings:\nReward - An item that has been given to you via the reward system. Rarities:\nWhite: Common, Blue: Rare, Orange: Legendary, Misfortune: Red, Grey: Armor, Turquoise: Spells\nMisfortune: An 'anti'-reward where you are penalized for losing by unequipping or stashing an equipped item.\nUnequip - Empty the slot the item is equipped in, keeping it in the inventory. Unless specified, the slot can be filled with another item but not the same one (until after the next fight).\nRemove / Stash - Put the item back into the storage. You may win it again.\nChallenge: A special misfortune type that limits your playstyle, but rewards you if you fulfill its conditions:\nWinning an encounter with the conditions active gives thhe respective additional rolls, but failing it forfeits any rolls you would have gained.\n\nAdditional stuff:\nRewards that you already have in your inventory are wasted.\nThe starting set / shortsword / shield are safe from stashing unless you want you're really hardcore I guess.\nIf you don't have an item it says and 'Go and fucking get it' isn't on the table, you may reroll.\nKilling furled fingers / hunters / the host and then dying means Win for every kill and then Lose for the death. There are no draws.\nYou can adjust the percentages of the different tiers in the options, there are also a lot of defaults.\nHave Fun and stay respectful.";

license = "Source code of website available at: \nImages were taken from the Eldenpedia at https://eldenring.wiki.gg/wiki/Eldenpedia. Many thanks to the members at Eldenpedia for giving the community a ton of information on the game!"

cookieDialogPre = "The following values will be saved:\n\n";

cookieDialogPost = "\n\nThese values will be saved to your computer via cookies. ONLY these values will be saved and no other personal information or any other, plus the information does not leave this computer. Proceed?";
